# Generated by Django 5.2.11 on 2026-02-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
        ('stores', '0002_alter_store_options_alter_store_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Складской остаток', 'verbose_name_plural': 'Остатки на складе'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение товара', 'verbose_name_plural': 'Движение товаров'},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='min_quantity',
            field=models.IntegerField(default=5, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('transfer', 'Перемещение'), ('write_off', 'Списание')], max_length=10, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Товар на складе'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'store')},
        ),
    ]
