# Generated by Django 5.2.11 on 2026-02-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_alter_store_is_active_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='floristprofile',
            options={'verbose_name': 'Профиль флориста', 'verbose_name_plural': 'Профили флористов'},
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='is_on_shift',
            field=models.BooleanField(default=False, verbose_name='На смене'),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='florists', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='floristprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='florist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
