# Generated by Django 5.2.11 on 2026-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_loyalty_confirmed',
            field=models.BooleanField(default=False, verbose_name='Карта подтверждена'),
        ),
    ]
