# Generated by Django 5.2.11 on 2026-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_price', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='Город')),
                ('remote_price', models.DecimalField(decimal_places=2, default=350, max_digits=10, verbose_name='Отдалённые районы')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0, help_text='0 = не используется', max_digits=10, verbose_name='Бесплатная доставка от')),
            ],
            options={
                'verbose_name': 'Настройки доставки',
                'verbose_name_plural': 'Настройки доставки',
            },
        ),
        migrations.CreateModel(
            name='FloristTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача флориста',
                'verbose_name_plural': 'Задачи флористов',
                'ordering': ['due_date', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_builder_enabled', models.BooleanField(default=True, verbose_name='Конструктор включен')),
                ('builder_min_price', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Минимальная цена сборки')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in_progress', 'Собирается'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery_city', 'Доставка (город)'), ('delivery_remote', 'Доставка (отдалённые)')], max_length=20)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('card_text', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_url', models.URLField(blank=True, help_text='Ссылка на оплату (генерируется автоматически)')),
                ('is_paid', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
