# Generated by Django 5.2.11 on 2026-02-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floristtask',
            options={'ordering': ['due_date', '-priority'], 'verbose_name': 'Задача флориста', 'verbose_name_plural': 'Задачи флористов'},
        ),
    ]
