# Generated by Django 5.2.11 on 2026-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('flower', 'Цветок'), ('greenery', 'Зелень'), ('wrap', 'Обёртка'), ('ribbon', 'Лента'), ('accessory', 'Аксессуар')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='components/')),
                ('color', models.CharField(blank=True, help_text='Цвет для фильтрации (hex или название)', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Компонент букета',
                'verbose_name_plural': 'Компоненты букетов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_photo', models.ImageField(blank=True, upload_to='bouquet_references/')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Пожелания клиента')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('florist_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от флориста')),
                ('florist_comment', models.TextField(blank=True, verbose_name='Комментарий флориста')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает оценки'), ('priced', 'Оценён флористом'), ('approved', 'Подтверждён клиентом'), ('ordered', 'В заказе'), ('cancelled', 'Отменён')], default='draft', max_length=15)),
                ('is_from_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кастомный букет',
                'verbose_name_plural': 'Кастомные букеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomBouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Элемент букета',
                'verbose_name_plural': 'Элементы букета',
            },
        ),
    ]
