# Generated by Django 5.2.11 on 2026-02-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouquet_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custombouquet',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_bouquets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custombouquetitem',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='bouquet_builder.custombouquet'),
        ),
        migrations.AddField(
            model_name='custombouquetitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouquet_builder.bouquetcomponent'),
        ),
        migrations.AddField(
            model_name='custombouquet',
            name='components',
            field=models.ManyToManyField(blank=True, through='bouquet_builder.CustomBouquetItem', to='bouquet_builder.bouquetcomponent'),
        ),
    ]
